project linter setup configuration
abenisamuel11/portfolio-project-for-mobile-version pull request #1
Opened 2023-04-29 15:32 UTC by abenisamuel11

## in this PR I add different features:
- set up project with linter configuration

2023-04-30 08:11 UTC, abenisamuel11 commented
## In this PR I add different features:
-**Header section** :
     -Html and CSS for code header section added.
-**Headline section**
    -HTML and CSS code for the headline section added
    -introduction, description, and social links with background image added.

2023-05-01 16:18 UTC, mukhammadrizooff requested changes
Hi @abenisamuel11, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 16:18 UTC, mukhammadrizooff commented on index.html
> +      <img src="./image/menu.png" alt="menu icon image" />
- [ ] [REQUIRED] Good job so far! The `hamburger` button should have a `nav` tag. The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-05-01 16:18 UTC, mukhammadrizooff commented on index.html
> +      <h2 class="Primay-text">I'm Abenezer.<br> Glad to see <br>you!</h2>
- [ ] [REQUIRED] Good job so far! The main title (e.g., "I'm Abenezer ...") should be a `h1` tag. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. The main title (e.g., "I'm Abenezer ...") is a h1 tag.

2023-05-01 23:10 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @abenisamuel11 👋

Good job so far implementing the changes suggested by the previous reviewer! I really appreciate the effort you put in!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏

- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters

However, there is always room for improvement.

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 23:10 UTC, KanzaTahreem commented on index.html
> +    </nav>
- [ ] Good job using the `nav` tag for `hamburger icon` 🥇 However, while implementing any change, please make sure to always follow the design guidelines. Right now, the toolbar is not styled as it was before 😓 See the images below for more clarity 👇 Please fix this

Your design previously | Your design now
---| ---|
![image](https://user-images.githubusercontent.com/106119105/235537663-a7ea4fd8-312f-404d-b61f-b540b89666d1.png) | ![image](https://user-images.githubusercontent.com/106119105/235537632-25fb1277-93ab-4c14-9ebd-e87a83a542dc.png)

- [OPTIONAL] I highly recommend to use `a` tag with `href` attribute for `logo`. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info ℹ

2023-05-01 23:10 UTC, KanzaTahreem commented on index.html
> +      </h3>
- [OPTIONAL] I think it would be better to use `p` tag for the paragraph for a semantic structure. This will also help search engines and screen readers to understand and categorize the content of your webpage 💪✨

2023-05-01 23:10 UTC, KanzaTahreem commented on style.css
> +
- [OPTIONAL] I think it would be better to avoid using margin, because there's a lot more space between toolbar and headline sections than needed according to the design guidelines ⛏🤓 See the images below 👇

Your design | Figma design 
---| ---|
![image](https://user-images.githubusercontent.com/106119105/235539026-1247659d-82f6-4e24-b430-09d8bc6fd5b1.png) |![image](https://user-images.githubusercontent.com/106119105/235539065-f15ddb76-c0f7-49f7-90f7-2a067f1997d6.png)

2023-05-02 15:12 UTC, Ibizugbe approved these changes
Hi @abenisamuel11 👋👋, 

![StandingOvationGIF (2)](https://user-images.githubusercontent.com/64643995/235708112-18e569d6-1489-4a2b-bfe9-59de565ebd7e.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅✅

- [x] Linters are passing👍.
- [x] The toolbar looks the way it was in the previous commit as requested by the previous reviewer👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 06:40 UTC, merged